### ISSUE TITLE
Make colour red

### ISSUE THREAD

**Issue by natbutter** [Sydney-Informatics-Hub/training.artemis.introhpc#11]
Can we make the style look like https://sydney-informatics-hub.github.io/geopython/
Maybe just swap out the css file? Or is there some setting I don't know. 

https://github.com/Sydney-Informatics-Hub/geopython/blob/main/_quarto.yml

**Comment by GiorgiaMori** [comment]
[This repo](https://github.com/Sydney-Informatics-Hub/training-template) gives you some options for changing themes. I thought we switched to blue last year?

**Comment by natbutter** [comment]
> [This repo](https://github.com/Sydney-Informatics-Hub/training-template) gives you some options for changing themes. I thought we switched to blue last year?

Ah right, that is why I tagged you. Easy. Blue is good too. Thankkkks

**Comment by GiorgiaMori** [comment]
I think it's okay to pick the colour you like the most!

**Comment by GiorgiaMori** [comment]
This option 

```
format:
  html:
    theme: simplex
    css: [lesson.css, bootstrap-icons.css]
    toc: true
    code-overflow: wrap
    highlight-style: github
```

works for the ochres.

I'll add the blue option too.
